services:
  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    command:
      - --default-time-zone='-03:00'
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  webapi:
    build: ./webapi
    container_name: ${PROJECT_NAME}_api
    environment:
      PORT: ${API_PORT}
      NODE_ENV: ${NODE_ENV}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    networks:
      - app-network

  presentation:
    build: ./presentation
    container_name: ${PROJECT_NAME}_frontend
    environment:
      VITE_API_URL: "http://localhost:${API_PORT}"
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - webapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
